class PakistanCities {
  static const List<String> cities = [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Rawalpindi',
    'Faisalabad',
    'Peshawar',
    'Quetta',
    'Multan',
    'Gujranwala',
    'Sialkot',
    'Sargodha',
    'Bahawalpur',
    'Sahiwal',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah',
    'Mirpur Khas',
    'Jacobabad',
    'Dera Ghazi Khan',
    'Sheikhupura',
    'Kasur',
    'Okara',
    'Rahim Yar Khan',
    'Mardan',
    'Abbottabad',
    'Kohat',
    'Mingora',
    'Chitral',
    'Gilgit',
    'Skardu',
    'Muzaffarabad',
    'Sialkot Cantonment',
    'Dera Ismail Khan',
    'Gujrat',
    'Chiniot',
    'Burewala',
    'Sadiqabad',
    'Tando Allahyar',
    'Tando Muhammad Khan',
    'Shikarpur',
    'Mianwali',
    'Khanewal',
    'Sargodha City',
    'Sukkur City',
    'Gujranwala City',
    'Bahawalnagar',
  ];
}
